import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<meta name="description" content="The Image to Code AI."></meta>
				<title>Berlin AI</title>
			</head>
			<body
				className={`bg-[#030301] relative after:absolute after:top-0 after:bottom-0 after:left-0 after:right-0 after:backdrop-blur-3xl after:z-[-1] after:pointer-events-none overflow-x-hidden max-w-full`}
			>
				<Header />
				{children}
			</body>
		</html>
	)
}
